3.12.1-ia64-hpux-v1

diff --git a/testsuite/makefiles/Makefile.several b/testsuite/makefiles/Makefile.several
--- a/testsuite/makefiles/Makefile.several
+++ b/testsuite/makefiles/Makefile.several
@@ -8,6 +8,8 @@ CMA_FILES=$(LIBRARIES:=.cma)
 CMXA_FILES=$(LIBRARIES:=.cmxa)
 O_FILES=$(C_FILES:=.o)
 
+SHELL=/usr/local/bin/zsh
+
 CUSTOM_FLAG=`if [ -z "$(C_FILES)" ]; then true; else echo '-custom'; fi`
 ADD_CFLAGS+=$(CUSTOM_FLAG)
 FORTRAN_LIB=`if [ -z "$(F_FILES)" ]; then true; else echo '$(FORTRAN_LIBRARY)'; fi`
@@ -19,7 +21,7 @@ check:
 
 run-all:
 	@for file in $(C_FILES); do \
-	  $(CC) -c -I$(PREFIX)/lib/ocaml/caml $$file.c; \
+	  $(CC) -c -I$(PREFIX)/lib/ocaml/caml $$file.c;\
 	done;
 	@for file in $(F_FILES); do \
 	  $(FORTRAN_COMPILER) -c -I$(PREFIX)/lib/ocaml/caml $$file.f; \
@@ -37,6 +39,7 @@ run-all:
 
 run-file:
 	@printf " $(DESC)"
+	@rm -f program || mv program `basename $(FILE) ml`program
 	@$(COMP) $(COMPFLAGS) $(FILE) -o program
 	@if [ -f `basename $(FILE) ml`runner ]; then \
 	  sh `basename $(FILE) ml`runner; \
@@ -46,8 +49,8 @@ run-file:
 	@if [ -f `basename $(FILE) ml`checker ]; then \
 	  sh `basename $(FILE) ml`checker; \
 	else \
-	  diff -q `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null || (echo " => failed" && exit 1); \
+	  cmp `basename $(FILE) ml`reference `basename $(FILE) ml`result > /dev/null || (echo " => failed" && exit 1); \
 	fi
 
 clean: defaultclean
-	@rm -f *.result ./program
+	@rm -f *.result; rm -f ./program
diff --git a/testsuite/makefiles/Makefile.toplevel b/testsuite/makefiles/Makefile.toplevel
--- a/testsuite/makefiles/Makefile.toplevel
+++ b/testsuite/makefiles/Makefile.toplevel
@@ -9,7 +9,7 @@ default:
 	done
 	@for file in *.reference; do \
 	  printf " ... testing '$$file':"; \
-	  diff -q $$file `basename $$file reference`result || (echo " => failed" && exit 1) && echo " => passed"; \
+	  cmp $$file `basename $$file reference`result || (echo " => failed" && exit 1) && echo " => passed"; \
 	done
 
 clean: defaultclean
